# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#name
name: "renovate"

# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#on
on:
  # run on every push to the default branch
  push:
    branches:
      - 'master'
  # run every Monday at 5 AM UTC
  schedule:
    - cron: '0 5 * * 1'
  # run manually
  workflow_dispatch:

# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobs
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions
jobs:
  renovate:
    runs-on: ubuntu-latest    
    permissions:
      contents: write
      issues: write
      pull-requests: write
      security-events: read
    steps:
      - uses: actions/checkout@v5
      - uses: renovatebot/github-action@v46.1.1
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_PLATFORM: github
          RENOVATE_ENDPOINT: ${{ github.api_url }}
          LOG_LEVEL: 'debug'
